name: Run action with provided version
on:
  pull_request:
  push:
    branches:
      - main
permissions: {}
jobs:
  runner:
    name: Run install-actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run action
        uses: ./
        with:
          version: 1.7.0
      - name: Run actionlint
        run: |
          actionlint --version

